### PR TITLE
Add the UAVMotionPoint message

### PR DESCRIPTION
**Pull request by aftersomemath**

### CODE REVIEW

**Comment by aftersomemath** [comment]
Opinions on having UAV on the front of the message? I'm leaning towards removing it.

**Comment by amiller27** [comment]
Yeah let's remove it

**Comment by aftersomemath** [comment]
Another thought, in MAVROS they handle large position messages where only some fields might be filled out with a bitfield. I'm thinking that this message should have that as well?

For instance:
http://docs.ros.org/api/mavros_msgs/html/msg/PositionTarget.html

**Comment by amiller27** [comment]
I like that bit field idea

**Comment by aftersomemath** [comment]
I think its a lot of work for something we will likely never use, I'd like to leave it out for now and just keep it as an idea. Is that good with you?

**Comment by aftersomemath** [comment]
It also adds a significant amount of data to each message

**Comment by aftersomemath** [comment]
Assuming the answer to the above question is yes, this is ready.

**Comment by asaba96** [comment]
Looks good to me. I really like this message. However, will not merge until Aaron is okay with leaving out the bit fields. I personally think they are excessive

**Pull request merged**
